export const MY_BOOK_LIST_REQUEST = 'MY_BOOK_LIST_REQUEST';
export const MY_BOOK_LIST_SUCCESS = 'MY_BOOK_LIST_SUCCESS';
export const MY_BOOK_LIST_FAIL = 'MY_BOOK_LIST_FAIL';

export const BOOK_CREATE_REQUEST = 'BOOK_CREATE_REQUEST';
export const BOOK_CREATE_SUCCESS = 'BOOK_CREATE_SUCCESS';
export const BOOK_CREATE_FAIL = 'BOOK_CREATE_FAIL';

export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST';
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS';
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL';

export const BOOK_DELETE_REQUEST = 'BOOK_DELETE_REQUEST';
export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS';
export const BOOK_DELETE_FAIL = 'BOOK_DELETE_FAIL';