export const MY_REVIEW_LIST_REQUEST = 'MY_REVIEW_LIST_REQUEST';
export const MY_REVIEW_LIST_SUCCESS = 'MY_REVIEW_LIST_SUCCESS';
export const MY_REVIEW_LIST_FAIL = 'MY_REVIEW_LIST_FAIL';

export const REVIEW_SAVE_REQUEST = 'REVIEW_SAVE_REQUEST';
export const REVIEW_SAVE_SUCCESS = 'REVIEW_SAVE_SUCCESS';
export const REVIEW_SAVE_FAIL = 'REVIEW_SAVE_FAIL';

export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST';
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS';
export const REVIEW_DELETE_FAIL = 'REVIEW_DELETE_FAIL';