export const TOUR_LIST_REQUEST = 'TOUR_LIST_REQUEST';
export const TOUR_LIST_SUCCESS = 'TOUR_LIST_SUCCESS';
export const TOUR_LIST_FAIL = 'TOUR_LIST_FAIL';

export const TOUR_DETAILS_REQUEST = 'TOUR_DETAILS_REQUEST';
export const TOUR_DETAILS_SUCCESS = 'TOUR_DETAILS_SUCCESS';
export const TOUR_DETAILS_FAIL = 'TOUR_DETAILS_FAIL';

export const TOUR_BOOKED_REQUEST = 'TOUR_BOOKED_REQUEST';
export const TOUR_BOOKED_SUCCESS = 'TOUR_BOOKED_SUCCESS';
export const TOUR_BOOKED_FAIL = 'TOUR_BOOKED_FAIL';

export const TOUR_TOP5_REQUEST = 'TOUR_TOP5_REQUEST';
export const TOUR_TOP5_SUCCESS = 'TOUR_TOP5_SUCCESS';
export const TOUR_TOP5_FAIL = 'TOUR_TOP5_FAIL';